.section .text
.globl _start
 
_start:
    li ra, -1
    slliw x2, x1, 8

.section .rodata
rodata_example:
    .asciz  "Hello, world!"       # Null-terminated string
 
.section .comment
    .asciz  "Generated by riscv64-unknown-elf-gcc"